// Modelos de ticket que vêm de fábrica — adaptados dos .txt do sistema legado
// (TICKETE, TICKETS, TICKET2, TICKETM, TICKRPS), mantendo os mesmos tokens e
// deixando de fora só os que não têm equivalente no esta hoje (código de
// barras, chancela, taxas do RPS, Sem Parar).
//
// Usados pelo botão "Restaurar modelo padrão" da tela de Modelos de ticket, e
// como ponto de partida quando a filial ainda não tem modelo próprio.

export const TIPOS_TICKET = [
  { tipo: 'entrada', rotulo: 'Entrada' },
  { tipo: 'saida', rotulo: 'Saída' },
  { tipo: 'segunda_via', rotulo: '2ª via (cliente perdeu o ticket)' },
  { tipo: 'mensalidade', rotulo: 'Recebimento de mensalidade' },
  { tipo: 'rps', rotulo: 'RPS / NFS-e' },
  { tipo: 'reserva', rotulo: 'Reserva de vaga' },
  { tipo: 'divida', rotulo: 'Dívida (saída paga como "Devedor")' },
];

const CABECALHO = [
  '@PG+@@ER@@PG-@',
  '@EE@',
  '@EC@',
  '@EG@-@EI@',
  '--------------------------------',
].join('\n');

export const MODELOS_PADRAO = {
  entrada: [
    CABECALHO,
    '@PG+@CONTROLE:@C#@@PG-@',
    '@SE(XBOX)@Box    : @XBOX@',
    'Placa  : @PG+@@CC@@PG-@',
    'Veiculo: @PG+@@CV@@PG-@',
    'Tabela : @TV@',
    '@SE(MENSALISTA)@Mensalista: @MENSALISTA@',
    'Entrada: @DE@ as @HE@ h.',
    '@SE(AVISO)@@AVISO@',
    '@SE(VALORSERVICOS_NUM)@Serv.: @SERVICOS@ = @VALORSERVICOS@',
    '@SE(VD_NUM)@DEVENDO: @VD@',
    '@SE(AVARIAS_NUM)@Avarias: @AVARIAS@',
    '--------------------------------',
    'Nao nos responsabilizamos por de',
    'feitos eletr./mecan. no veiculo.',
    '--------------------------------',
    'Voce foi atendido por @US@',
  ].join('\n'),

  saida: [
    CABECALHO,
    '@PG+@SAIDA:@C#@@PG-@',
    '',
    'Placa  : @PG+@@CC@@PG-@',
    'Veiculo: @PG+@@CV@@PG-@',
    '@SE(MENSALISTA)@Mensalista: @MENSALISTA@',
    'Entrada: @DE@ as @HE@ h.',
    'Saida  : @DS@ as @HS@ h.',
    'Perman.: @TH@',
    '@SE(VALORSERVICOS_NUM)@Serv.: @SERVICOS@ = @VALORSERVICOS@',
    '@SE(VC_NUM)@Convenio @CO@: -@VC@',
    '@SE(VD_NUM)@Divida ant.: +@VD@',
    '@SE(BONUS_NUM)@Bonus  : @BONUS@',
    '@SE(SALDOBONUS_NUM)@Saldo bonus: @SALDOBONUS@ pontos',
    '@PG+@Valor  : @V@@PG-@',
    '--------------------------------',
    'Voce foi atendido por @US@',
  ].join('\n'),

  segunda_via: [
    CABECALHO,
    '@PG+@CONTROLE:@C#@@PG-@',
    '       (2a.Via)',
    'Placa  : @PG+@@CC@@PG-@',
    'Veiculo: @PG+@@CV@@PG-@',
    '@SE(MENSALISTA)@Mensalista: @MENSALISTA@',
    'Entrada: @DE@ as @HE@ h.',
    '--------------------------------',
    'Voce foi atendido por @US@',
    '--------------------------------',
    '',
    'Nome : _________________________',
    '',
    'R.G. : _________________________',
    '',
    'Fone : _________________________',
    '',
    'Doc. Veiculo : _________________',
    '',
    'Data da retirada : ___/___/_____',
    '',
    '  Declaro que perdi o comprovante',
    '  de estacionamento e retirei o',
    '  veiculo mediante a apresentacao',
    '  dos documentos acima.',
    '@P2@',
    '  ______________________________',
    '            Assinatura',
  ].join('\n'),

  mensalidade: [
    CABECALHO,
    '',
    '   PAGAMENTO DE MENSALIDADE',
    '',
    '        RECIBO : @C#@',
    '',
    '@MENSALISTA@',
    '@SE(MCPF)@CPF/CNPJ: @MCPF@',
    '',
    '@SE(CC01)@@CC01@ - @CV01@',
    '@SE(CC02)@@CC02@ - @CV02@',
    '@SE(VAGAS)@Vagas contratadas: @VAGAS@',
    '',
    'DATA PAGAMENTO......: @DE@',
    'DATA PROX.VENCIMENTO: @DS@',
    '',
    'VALOR MENSALIDADE...: @VM@',
    '@SE(MULTA_NUM)@MULTA/JUROS.........: @MULTA@',
    '@SE(EXTRA_NUM)@EXTRAS..............: @EXTRA@',
    '                      ---------',
    '@PG+@VALOR PAGO .........: @V@@PG-@',
    'Forma: @MOEDA@',
    '--------------------------------',
    'Voce foi atendido por @US@',
  ].join('\n'),

  rps: [
    '@PG+@RECIBO PROVISORIO@PG-@',
    '@PG+@ DE SERVICOS-RPS@PG-@',
    '@PG+@ No. : @NNFE@@PG-@',
    '@PG+@ Serie : @SERIERPS@@PG-@',
    '',
    '*Prestador do Servico',
    'R.Social.: @RAZAORPS@',
    'Endereco.: @EE@',
    'Municipio: @EC@',
    'C.N.P.J..: @EG@',
    'I.Munic..: @IMRPS@',
    '',
    // A nota tanto pode vir de uma saída do pátio quanto de um recebimento de
    // mensalidade — as duas seções abaixo se excluem pela condicional.
    '@SE(#MENSALIDADE)@*Comprovante',
    '@SE(#MENSALIDADE)@Numero...: @PG+@@C#@@PG-@',
    '@SE(#MENSALIDADE)@Chapa....: @PG+@@CC@@PG-@',
    '@SE(#MENSALIDADE)@Veiculo..: @PG+@@CV@@PG-@',
    '@SE(#MENSALIDADE)@Entrada..: @DE@ as @HE@ h.',
    '@SE(#MENSALIDADE)@Saida....: @DS@ as @HS@ h.',
    '@SE(#MENSALIDADE)@Perman...: @TH@',
    '@SE(#MENSALIDADE)@Valor....: @V@',
    '@SE(MENSALIDADE)@*Mensalidade',
    '@SE(MENSALIDADE)@Competenc: @COMPETENCIA@',
    '@SE(MENSALIDADE)@Valor....: @PG+@@V@@PG-@',
    '',
    '*Tomador do Servico',
    '@SE(CCPF)@CPF/CNPJ : @CCPF@',
    '@SE(CNOME)@Nome.... : @CNOME@',
    '@SE(CENDE)@Endereco : @CENDE@, @CNUM@',
    '@SE(CBAIRRO)@Bairro...: @CBAIRRO@',
    '@SE(CCEP)@C.E.P....: @CCEP@',
    '@SE(CCID)@Cidade...: @CCID@-@CESTA@',
    '@SE(CFONE)@Telefone.: @CFONE@',
    '@SE(CEMAIL)@E-Mail...: @CEMAIL@',
    '',
    '*Discriminacao do Servico',
    'Desc.Serv: @RPSDESCR@',
    'Vlr.Serv.: @V@',
    '% ISS....: @PERCISS@',
    'Vlr.ISS..: @ISS@',
    '--------------------------------',
  ].join('\n'),

  reserva: [
    CABECALHO,
    '@PG+@RESERVA DE VAGA@PG-@',
    '',
    'Placa  : @PG+@@CC@@PG-@',
    'Veiculo: @CV@',
    'Tipo   : @RTIPO@',
    'De     : @RDE@',
    'Ate    : @RATE@',
    'Nome   : @RNOME@',
    'Fone   : @RFONE@',
    '@SE(ROBS)@Obs.: @ROBS@',
    '@SE(PROPOSTO)@Vlr.proposto: @PROPOSTO@',
    '@SE(ANTECIPADO)@Vlr.antecipado: @ANTECIPADO@',
    '--------------------------------',
    'Voce foi atendido por @US@',
  ].join('\n'),

  // Impresso na hora que a saída é paga (total ou parcialmente) com a forma
  // "Devedor" — o valor vira saldo devedor da placa (ver Cadastros → Formas
  // de pagamento), cobrado junto com a próxima estadia (token @VD@ no
  // ticket de entrada/saída seguinte). Equivalente ao TICKETD.TXT do legado.
  divida: [
    CABECALHO,
    '@PG+@TICKET DE DIVIDA@PG-@',
    '',
    'Placa  : @PG+@@CC@@PG-@',
    'Veiculo: @CV@',
    'Data   : @DS@ as @HS@ h.',
    '@PG+@Valor devido: @DIVIDA@@PG-@',
    '--------------------------------',
    'Pague este valor na proxima vez',
    'que este veiculo entrar.',
    '--------------------------------',
    'Voce foi atendido por @US@',
  ].join('\n'),
};
